# -*- coding: utf-8 -*-
"""Ejercicio, Clase 03-09-26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSqWqNRoAkaL1CjdCoiSe-1DGP-hOopb

**Ejercicios 03-09-26.**
"""

#1. Completa la condición para mostrar “Mayor de edad” cuando la variable edad sea mayor o
#igual a 18.

edad = 20

if edad >= 18:
    print("Mayor de edad")

#2. Completa la estructura para clasificar una temperatura como “Alta” si supera 30 grados y
#“Normal” en caso contrario.

temperatura = 31

if temperatura > 30:
    print("Alta")
else:
    print("Normal")

#3. Sin ejecutar, escribe exactamente qué imprimirá el programa.

t = float(input('numero: '))

numero = 7
if numero % 2 == 0:
 print("Par")
else:
 print("Impar")

#4. Agrega las dos expresiones faltantes para clasificar la nota.

nota = 4.2

if nota >= 4.5:
 print("Excelente")
elif nota >= 4.0:
 print("Muy buen desempeño")
elif nota >= 3.0:
 print("Aprobado")
else:
 print("No aprobado")

#5. El programa pretende mostrar “Excelente” para notas de 4.5 o más. Reescribe únicamente el
#bloque condicional en el orden correcto.

nota = float(input('Notas: '))

#nota = 4.8

if nota >= 4.5:
 print("Excelente")
elif nota >= 3.0:
 print("Aprobado")

#6. Escribe la salida para valor = 12. Después indica cuál condición fue la primera verdadera.

nota = float(input('valor: '))

valor = 12

if valor < 15:
 print("A")
elif valor < 10:
 print("B")
elif valor < 5:
 print("C")
else:
 print("D")

#7. Completa el operador lógico para permitir acceso solo cuando ambas variables sean
#verdaderas.

usuario_activo = True
tiene_permiso = True

if usuario_activo and tiene_permiso:
 print("Acceso permitido")
else:
 print("Acceso denegado")

#8. Completa la condición: se permite continuar si existe correo válido o teléfono válido.

correo_valido = True
telefono_valido = True

if correo_valido and telefono_valido :
 print("Continuar registro")
else:
 print("Faltan datos de contacto")

#9. Completa la condición usando not para mostrar el mensaje solo si la cuenta NO está
#bloqueada.

cuenta_bloqueada = False
if not cuenta_bloqueada:
 print("Puede operar")

#10. Completa range() para imprimir los valores 1, 2, 3, 4 y 5.

for numero in range(1, 6):
 print(numero)

#11. Completa range() para imprimir 2, 4, 6, 8 y 10.

for numero in range(2, 11, 2):
 print(numero)

#12. Sin ejecutar, determina el valor final de suma.

suma = 0
for i in range(1, 4):
 suma = suma + i
print(suma)

#13. Completa la condición y la actualización para imprimir los números del 1 al 5.

numero = 1
while numero <= 5:
 print(numero)
 numero += 1

#14. El siguiente programa nunca termina. Corrige solo la línea que falta dentro del ciclo.

numero = 1
while numero <= 5:
 print(numero)

#15. Completa el ciclo para permitir máximo 3 intentos. No modifiques las líneas ya escritas.

intentos = 3
while intentos > 0:
 clave = input("Ingrese la clave: ")
 intentos -= 1
print("Proceso finalizado")

#16. ¿for o while?
#Escribe la estructura que elegirías en cada situación.

#Situación for / while
#Procesar exactamente 10 mediciones. FOR
#Pedir una clave hasta que sea correcta. WHILE
#Imprimir los números del 1 al 20. FOR
#Repetir un cálculo hasta que el error sea menor que 0.01. WHILE

#17. Completa el programa para recorrer del 1 al 12 y mostrar únicamente los múltiplos de 3.
for numero in range(1, 13):
 if numero % 3 == 0:
  print(numero)

#18. Escribe todas las líneas que producirá el programa.
for numero in range(1, 8):
 if numero < 3:
  print(numero, "A")
 elif numero < 6:
  print(numero, "B")
 else:
  print(numero, "C")

#19. Completa el código Python para que represente exactamente el pseudocódigo mostrado.
#PSEUDOCÓDIGO
#LEER nota
#SI nota >= 3.0 ENTONCES
#ESCRIBIR "Aprobado"
#SI NO
#ESCRIBIR "No aprobado"
#FIN SI

#PYTHON
nota = float(input("Nota: "))
if nota >= 3.0:
 print("Aprobado")
else:
 print("No aprobado")

#20. Completa el programa Python equivalente al pseudocódigo.
#PSEUDOCÓDIGO
#PARA i DESDE 1 HASTA 5 HACER
#ESCRIBIR i
#FIN PARA

#PYTHON
for i in range(1, 6):
 print(i)

#21. Completa todos los espacios. Antes de ejecutar, prueba mentalmente tu solución con los
#valores: 15, 18, 22, 25 y 30.

# El programa debe solicitar 5 temperaturas.
# Para cada una debe mostrar:
# "Baja" si t < 18
# "Normal" si 18 <= t <= 25
# "Alta" si t > 25

for i in range(5):
 t = float(input("Temperatura: "))

if t <18:
 print("Baja")
elif t <=25:
 print("Normal")
else:
 print(Alta)

"""Autoevaluación rápida
1. ¿Puedo explicar cuándo usar if, elif y else?
2. ¿Puedo distinguir cuándo conviene for y cuándo while?
3. ¿Puedo identificar el riesgo de un ciclo infinito?
4. ¿Puedo traducir una decisión o repetición desde pseudocódigo a Python?

**RPTA.**
1. if, elif y else sirven para tomar decisiones.
2. for repite una cantidad conocida; while repite mientras se cumpla una condición.
3. Un ciclo infinito nunca termina.
4. if/elif/else = decisiones; for/while = repeticiones.

"""