# -*- coding: utf-8 -*-
"""Ejercicio3, Clase 11-09-26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3XB4Xz_N8hC6jX3UrM31K7FNSw3Ymss
"""

#1. Complete la palabra clave que define una función.
#Complete la palabra clave que define una función.

def saludar():
 print("Hola")
saludar()

#2. Complete la línea que ejecuta la función ya definida.

def bienvenida():
 print("Bienvenido al curso")
bienvenida()

#3. Sin ejecutar, determine en qué orden aparecen los mensajes.
def uno():
 print("A")
print("B")
uno()
print("C")

#4. El programa falla porque la función se llama antes de existir. Reescriba el bloque completo
#en el orden correcto.

def saludar(nombre):
 print("Hola,", nombre)
saludar("Ana")

#5. Complete el parámetro que recibe la función.

def saludar(nombre):
 print("Hola,", nombre)
saludar("Ana")

#6. Complete los parámetros necesarios para calcular el área.

def area(base, altura):
    return base * altura

print(area(3, 4))

#7. Complete los argumentos para obtener exactamente el resultado indicado.

def area(base, altura):
 return base * altura
print(area(5, 5)) # 25.0

#8. Llame tres veces a la misma función con precios distintos.

def con_iva(precio):
 return precio * 1.19
print(con_iva(100))
print(con_iva(200))
print(con_iva(300))

#9. Observe la definición y la llamada, y distinga cada uno de los dos nombres.

def doble(n):
 return n * 2
resultado = doble(5)

#10. Complete la llamada para que se imprima: Ana 20 Bogota

(nombre, edad, ciudad):
 print(nombre, edad, ciudad)
perfil(___, ___, ___)

#11. Complete los nombres de los parámetros para que el orden deje de importar.

def perfil(nombre, edad, ciudad):
 print(nombre, edad, ciudad)
perfil(edad=20, nombre="Ana", ciudad="Bogota")

#12. Complete el valor por defecto del parámetro saludo.

def saludar(nombre, saludo="Hola"):
    print(saludo, nombre)

saludar("Ana")

#13. Complete el argumento que sustituye al saludo por defecto.

def saludar(nombre, saludo="Buen día"):
 print(saludo, nombre)
saludar("Luis", "Buen día")

#14. El siguiente encabezado produce un error. Reescriba la definición completa de forma
#correcta.

def registrar(cantidad=1, producto):
 print(producto, cantidad)

#15. Complete el recorrido para sumar todos los precios recibidos.

def total(precios):
 suma = 0
 for p in precios:
  suma = suma + p
 return suma
print(total([1200, 950, 3400]))

#16. Complete la palabra clave que entrega el resultado.

def doble(n):
 return n * 2
print(doble(5))

#17. Complete la llamada para guardar el resultado y operar con él.

def doble(n):
 return n * 2
resultado = doble(6)
print(resultado + 1)

#18. Sin ejecutar, determine qué imprimen las dos últimas líneas.

def saludo(nombre):
 print("Hola,", nombre)
x = saludo("Ana")
print(x)

#19. La suma falla. Corrija la función para que el resultado pueda seguir usándose y escriba la
#versión corregida.

def doble(n):
    return n * 2

total = doble(5) + 3
print(total)

#20. Complete la instrucción que devuelve el segundo resultado.

def signo(n):
 if n < 0:
  return "negativo"
 return "positivo"

print(signo(-4))
print(signo(7))

#21. Sin ejecutar, determine qué se imprime y qué línea nunca se ejecuta.

def prueba(n):
 if n > 0:
  return "positivo"
 print("linea intermedia")
 return "otro"
print(prueba(5))

#22. Complete la función para que entregue el mínimo y el máximo.

def resumen(valores):
 return min(valores), max(valores)
menor, mayor = resumen([8, 3, 10, 5])
print(menor, mayor)

#23. Complete la llamada interna para calcular el precio con IVA redondeado.

def con_iva(p):
 return p * 1.19
def redondear(valor):
 return round(valor, 2)
print(redondear(con_iva(1200)))

#24.Sin ejecutar, determine qué imprime cada una de las dos llamadas.

mensaje = "global"

def prueba():
 mensaje = "local"
 print(mensaje)
prueba()
print(mensaje)

#25. Reescriba la función para que reciba el IVA como parámetro y no dependa de una variable
#externa.

def con_iva(precio, iva):
    return precio * (1 + iva)

iva = 0.19
precio = 10000

total = con_iva(precio, iva)
print(total)

#26. Complete la función para que devuelva una lista nueva sin alterar la que recibe.

def agregar(lista):
 nueva = lista + [agregar]
 return nueva
datos = [1, 2]
print(agregar(datos))
print(datos)

#27. Complete la función que calcula el promedio de una lista de notas.

def promedio(notas):
    total = 0
    for n in notas:
        total = total + n
    return total / len(notas)

print(promedio([3.5, 4.2, 2.8]))

#28.Complete las claves para mostrar el nombre y la nota del estudiante.

def describir(alumno):
    print(alumno["nombre"], alumno["nota"])

describir({"nombre": "Laura", "nota": 4.6})

#29. Complete el método que agrega elementos y el valor que se devuelve.

def aprobados(estudiantes):
    resultado = []
    for e in estudiantes:
        if e["nota"] >= 3.0:
            resultado.append(e["nombre"])
    return resultado

datos = [
    {"nombre": "Ana", "nota": 4.2},
    {"nombre": "Luis", "nota": 2.8}
]

print(aprobados(datos))

#30. Complete el programa que calcula el promedio de un estudiante, decide si aprueba y
#muestra el reporte usando tres funciones.

def promedio(notas):
    total = 0
    for n in notas:
        total = total + n
    return total / len(notas)

def aprueba(prom, minimo=3.0):
    return prom >= minimo

def reporte(nombre, notas):
    prom = promedio(notas)
    print(nombre, round(prom, 2))
    if aprueba(prom):
        print("Aprobado")
    else:
        print("No aprobado")

reporte("Laura", [3.5, 4.2, 2.8])

"""Autoevaluación rápida
1. ¿Puedo definir una función y llamarla en el orden correcto?
2. ¿Puedo distinguir entre un parámetro y un argumento?
3. ¿Puedo explicar la diferencia entre print y return?
4. ¿Puedo decidir cuándo conviene extraer una función?

**RPTA.**
1. Sí. Puedo definir una función primero y luego llamarla para ejecutar las instrucciones que contiene.
2. Sí. El parámetro es la variable que se define dentro de la función, mientras que el argumento es el valor que se entrega cuando se llama la función.
3. Sí. `print` muestra un resultado en pantalla, mientras que `return` devuelve un valor que puede ser utilizado posteriormente en el programa.
4. Sí. Conviene crear una función cuando una tarea se repite, cuando un bloque de código puede reutilizarse o cuando ayuda a organizar y hacer más claro el programa.


"""